import { 
  LayoutDashboard, 
  History, 
  ClipboardList, 
  Package, 
  LineChart, 
  Factory, 
  Truck, 
  Banknote, 
  Download, 
  Search, 
  Trash2,
  MapPin,
  Phone,
  MessageSquare,
  Flame,
  Star,
  Award,
  Gem,
  CheckCircle2,
  AlertTriangle,
  RotateCcw,
  XCircle,
  PlusCircle,
  TrendingUp,
  User,
  Users,
  Timer,
  ShoppingBag,
  Zap,
  Printer,
  ChevronRight,
  ShieldCheck,
  Ban,
  Medal,
  Check,
  Pencil
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  History: History,
  Orders: ClipboardList,
  Products: Package,
  Analytics: LineChart,
  Manufacturing: Factory,
  Delivery: Truck,
  Money: Banknote,
  Export: Download,
  Search: Search,
  Delete: Trash2,
  Edit: Pencil,
  MapPin: MapPin,
  Phone: Phone,
  WhatsApp: MessageSquare,
  Flame: Flame,
  Star: Star,
  Award: Award,
  Gem: Gem,
  CheckCircle: CheckCircle2,
  Alert: AlertTriangle,
  Undo: RotateCcw,
  Cancel: XCircle,
  Add: PlusCircle,
  Trending: TrendingUp,
  User: User,
  Users: Users,
  Timer: Timer,
  Bag: ShoppingBag,
  Zap: Zap,
  Print: Printer,
  Next: ChevronRight,
  Trust: ShieldCheck,
  Ban: Ban,
  Medal: Medal,
  Check: Check
};
